const EVENTS = {
    CONNECT: 'connect',
    DISCONNECT: 'disconnect',
    CONNECTION: 'connection',
    AUTHORIZE: 'AUTHORIZE',
    AUTHORIZE_SUCCESSFUL: 'AUTHORIZE_SUCCESSFUL',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NEW_USER_CONNECTED: 'NEW_USER_CONNECTED',
    CREATE_POST: 'CREATE_POST',
    BROADCAST_POST: 'BROADCAST_POST',
    SEND_LIKE: 'SEND_LIKE',
    LIKE_SAVED: 'LIKE_SAVED',
    POST_UPDATED: 'POST_UPDATED',
    DELETE_POST: 'DELETE_POST'
};

exports.EVENTS = EVENTS;