export const EVENTS = {
    CONNECT: 'connect',
    DISCONNECT: 'disconnect',
    CONNECTION: 'connection',
    AUTHORIZE: 'AUTHORIZE',
    AUTHORIZE_SUCCESSFUL: 'AUTHORIZE_SUCCESSFUL',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NEW_USER_CONNECTED: 'NEW_USER_CONNECTED',
    CREATE_POST: 'CREATE_POST',
    BROADCAST_POST: 'BROADCAST_POST'
};